/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oWwvoKuXjHMyiEVNYgMWEB
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantssytZ4QjFWalC } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: SytZ4qjFWalC/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantssytZ4QjFWalC
});
